<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">

<style>

body{
font-family: DejaVu Sans, sans-serif;
font-size:12px;
color:#222;
}

.header{
background:#111;
color:#D6BB00;
padding:20px;
}

.header h1{
margin:0;
font-size:22px;
}

.section{
margin-top:20px;
}

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
}

th{
background:#D6BB00;
color:#111;
padding:10px;
text-align:left;
}

td{
padding:8px;
border-bottom:1px solid #ddd;
}

.summary{
background:#F9F5DD;
padding:15px;
border-left:6px solid #D6BB00;
}

.footer{
margin-top:40px;
text-align:center;
font-size:10px;
color:#777;
}

</style>

</head>

<body>

<div class="header">

<h1>Stremvans Funds Management Limited</h1>

<p>Investor Portfolio Statement</p>

</div>

<div class="section">

<h3>Investor Details</h3>

<table>

<tr>
<td><strong>Name</strong></td>
<td>{{ $client->first_name }} {{ $client->last_name }}</td>
</tr>

<tr>
<td><strong>Client Code</strong></td>
<td>{{ $client->client_code }}</td>
</tr>

<tr>
<td><strong>Email</strong></td>
<td>{{ $client->email }}</td>
</tr>

<tr>
<td><strong>Phone</strong></td>
<td>{{ $client->phone }}</td>
</tr>

</table>

</div>

<div class="section summary">

<h3>Portfolio Summary</h3>

<p><strong>Total Investments:</strong>
{{ $client->portfolios->count() }}</p>

<p><strong>Total Amount Invested:</strong>

₦{{ number_format($client->portfolios->sum('amount_invested'),2) }}

</p>

</div>

<div class="section">

<h3>Investment Portfolio</h3>

<table>

<thead>

<tr>
<th>Fund</th>
<th>Type</th>
<th>Amount</th>
<th>Status</th>
</tr>

</thead>

<tbody>

@foreach($client->portfolios as $portfolio)

<tr>

<td>{{ $portfolio->fund_name }}</td>

<td>{{ $portfolio->investment_type }}</td>

<td>₦{{ number_format($portfolio->amount_invested,2) }}</td>

<td>{{ $portfolio->status }}</td>

</tr>

@endforeach

</tbody>

</table>

</div>

<div class="section">

<h3>Transaction History</h3>

<table>

<thead>

<tr>

<th>Date</th>

<th>Reference</th>

<th>Type</th>

<th>Amount</th>

</tr>

</thead>

<tbody>

@foreach($client->portfolios as $portfolio)

@foreach($portfolio->transactions as $transaction)

<tr>

<td>{{ $transaction->transaction_date }}</td>

<td>{{ $transaction->reference }}</td>

<td>{{ $transaction->transaction_type }}</td>

<td>₦{{ number_format($transaction->amount,2) }}</td>

</tr>

@endforeach

@endforeach

</tbody>

</table>

</div>

<div class="section">

<h3>Compliance Summary</h3>

<table>

<thead>

<tr>
<th>Document</th>
<th>Status</th>
</tr>

</thead>

<tbody>

@foreach($client->complianceDocuments as $doc)

<tr>

<td>{{ $doc->document_type }}</td>

<td>{{ $doc->status }}</td>

</tr>

@endforeach

</tbody>

</table>

</div>

<div class="footer">

Generated by Stremvans CRM • {{ now()->format('d M Y H:i') }}

</div>

</body>

</html>